"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { Header } from "./header";
import { useContext, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { UserContext, UserContextProvider } from "./userContextProvider";
import { QueryClient, QueryClientProvider, useQuery } from "react-query";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Instabook",
  description: "Generated by create next app",
};

const queryClient = new QueryClient();

declare global {
  interface Window {
    Kakao: any;
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const router = useRouter();

  // const [token, setToken] = useState<string | null>();
  const userId = useContext<number | null>(UserContext);

  useEffect(() => {
    window.Kakao.init(process.env.KAKAO_KEY);

    const token = sessionStorage.getItem("access-token");
    if (token) {
      // 로그인된 상태이므로 다음 경로로 리다이렉트 또는 필요한 작업을 수행합니다.
      // const request = await axios.get()
      // setToken(accessToken);
    } else {
      router.push("/auth/login");
      // setToken(null);
    }
  }, []);

  return (
    <html lang="en">
      <head>
        <script src="https://developers.kakao.com/sdk/js/kakao.js"></script>
      </head>
      <body className={inter.className}>
        <main
          className="flex min-h-screen flex-col justify-between"
          style={{ backgroundColor: "white" }}
        >
          {" "}
          <div>
            <UserContextProvider>
              <QueryClientProvider client={queryClient}>
                <Header />
                <div className="max-h-[800px] overflow-y-auto">{children}</div>
              </QueryClientProvider>
            </UserContextProvider>
          </div>
        </main>
      </body>
    </html>
  );
}
